<?php

/**
 * @file
 * Expand formatter module hooks.
 */

/**
 * Implements hook_theme().
 */
function expand_formatter_theme($existing, $type, $theme, $path) {

  return [
      'expandformatter' => [
          'variables' => [
          'attributes' => [],
          'ellipsis' => '…',
          'contentdata' => NULL,
          'summarydata' => NULL,
          'triggerclass' => NULL,
        ],
      ],
  ];
}
